### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by simonlbn** [adafruit/Adafruit_Seesaw#1]
Hi,

This repository doesn't have a license file, and there aren't license headers in the main source files.

Could an explicit license be added?

Thanks.
Simon

**Comment by deanm1278** [comment]
updated! https://github.com/adafruit/Adafruit_Seesaw/commit/4c15506517df1394ef7c1ea51842377751da20ea

**Comment by simonlbn** [comment]
Thanks!
