### ISSUE TITLE
1.8" TFT shield v2: How to dim?

### ISSUE THREAD

**Issue by Ve2mrx** [adafruit/Adafruit_Seesaw#10]
Hi!
  Could it be possible to add some information on how to dim the backlight on the 1.8" TFT shield v2?

- [ ] Maybe an example in [shieldtest.ino](https://github.com/adafruit/Adafruit_Seesaw/blob/master/examples/TFTShield18/shieldtest/shieldtest.ino)
- [ ] Some comments in the header/cpp files

Thanks!
  Martin

**Comment by ladyada** [comment]
added here!
https://github.com/adafruit/Adafruit-ST7735-Library/blob/master/examples/TFTShield18_seesaw/shieldtest/shieldtest.ino
