### ISSUE TITLE
seewaw not find it on default address..

### ISSUE THREAD

**Issue by yo2ldk** [adafruit/Adafruit_Seesaw#102]
looking further, I find that my ESP32 board (M5Stack Atom Lite), using YOUR example - encoder_basic- ,
 not find your I2C - Adafruit I2C Quad Rotary Encoder

"rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
Looking for seesaw!
Couldn't find seesaw on default address"

even if I declare it
#include "Adafruit_seesaw.h"
#include <seesaw_neopixel.h>

#define SS_SWITCH        12
#define SS_NEOPIX        6
#define SEESAW_ADDR          0x49
where is declared PIN A and PIN B in ALL your examples ??
once again,on ALL your example, I find just for switch,neopix led,and all possible, EXCEPT  a good example for ENCODER, because i buy it just for that: to use it as I2C ENCODER !!  as is name you give it..

**Comment by caternuson** [comment]
What happens if you run the example from the guide?
https://learn.adafruit.com/adafruit-i2c-quad-rotary-encoder-breakout/arduino

**Comment by yo2ldk** [comment]
> What happens if you run the example from the guide? https://learn.adafruit.com/adafruit-i2c-quad-rotary-encoder-breakout/arduino

  Thank you for fast reply,
  this is problem, nothing happens, declared as:       #define SEESAW_ADDR      0x49,
  on serial have follow message:
  
  "configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
Looking for seesaw!
Couldn't find seesaw on default address
"

**Comment by caternuson** [comment]
Does the address show up in an I2C scan?
https://learn.adafruit.com/scanning-i2c-addresses/arduino

**Comment by yo2ldk** [comment]
it is present at 0x49
![i2c](https://github.com/adafruit/Adafruit_Seesaw/assets/1875591/6a9a6947-7ab6-4d0b-b359-b49a60ba4cb4)

**Comment by caternuson** [comment]
Weird. It's showing up in the I2C scan as expected. So unclear why the example code is not working.

Is the M5Stack Atom Lite your only Arduino board?

**Comment by yo2ldk** [comment]
no, I have also others boards, I will try when I have time but, 
I need for Atom Lite because not have enough IO ports,
 more exactly is Atom lite HDMI display, and all his ports is for that driver

**Comment by yo2ldk** [comment]
ok, this issue will be closed, I found the problem
If your I2C encoders boards is not recognised on I2C, 
just add on void setup the line
"Wire.begin(25, 21);"  where 25,21 is YOUR  xx, xx arduino board SDA, SCL pinout numbers.
