### ISSUE TITLE
Travis fails due to missing file Adafruit_RGBTrellis.h

### ISSUE THREAD

**Issue by TheKitty** [adafruit/Adafruit_Seesaw#13]
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
_basic_multi:_1:33: error: Adafruit_RGBTrellis.h: No such file or directory
compilation terminated.
exit status 1

Looks like someone is preparing for a new board and pushed a file (without the .h accompanying. This makes other pull requests like mine (for a touch example) fail.

**Comment by deanm1278** [comment]
this is fixed, although travis is currently still failing due to something wrong w/ the setup (probably caching)

**Comment by ladyada** [comment]
fixed, thanks

@deanm1278 wanna do a version bump on this library?

**Comment by deanm1278** [comment]
bumped!
