### ISSUE TITLE
Calls to analog_write require a delay

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Seesaw#17]
More info here:
https://forums.adafruit.com/viewtopic.php?f=19&t=144068
I've also recreated the issue.

Multiple calls to`analog_write` generate an IOError. Adding a `time.sleep` between calls fixes it.

**Comment by deanm1278** [comment]
hey can you re-open this issue on this repo? https://github.com/adafruit/Adafruit_CircuitPython_seesaw

**Comment by caternuson** [comment]
Oops. Yep. Sry.
