### ISSUE TITLE
Adafruit STEMMA Soil Sensor - I2C Capacitive Moisture Sensor

### ISSUE THREAD

**Issue by patrickadep2018** [adafruit/Adafruit_Seesaw#22]
Anyone have any idea how to calibrate the Adafruit STEMMA Soil Sensor - I2C Capacitive Moisture Sensor to give VWC (Voulmetric water content) 
this is the code used:

#include "Adafruit_seesaw.h"

Adafruit_seesaw ss;

void setup() {
  Serial.begin(115200);

  Serial.println("seesaw Soil Sensor example!");
  
  if (!ss.begin(0x36)) {
    Serial.println("ERROR! seesaw not found");
    while(1);
  } else {
    Serial.print("seesaw started! version: ");
    Serial.println(ss.getVersion(), HEX);
  }
}

void loop() {
  float tempC = ss.getTemp();
  uint16_t capread = ss.touchRead(0);

  Serial.print("Temperature: "); Serial.print(tempC); Serial.println("*C");
  Serial.print("Capacitive: "); Serial.println(capread);
  delay(100);
}

**Comment by ladyada** [comment]
totally not possible. its only a capacitive measurement - you could try to calibrate it against a known source but its totally 100% not guaranteed :)
