### ISSUE TITLE
Set Encoder pins

### ISSUE THREAD

**Issue by Sindel** [adafruit/Adafruit_Seesaw#30]
I saw in the repo that there is a functionality and even an example to use an encoder, but I cannot find how I can specify the Pins (A and B). I have a Seesaw breakout module. Could anyone point me to how to set the pins?

**Comment by ladyada** [comment]
hi it has to be set it the firmware, and the firmware recompiled, not able to do dynamically
https://github.com/adafruit/seesaw/blob/master/boards/encoder/board_config.h#L52
