### ISSUE TITLE
Seesaw soil sensor not measuring capacitance; only temperature

### ISSUE THREAD

**Issue by juliant99** [adafruit/Adafruit_Seesaw#39]
I used the seesaw soil sensor example which comes with version 1.4.0 of the soli sensor library and the capacitance logged is the same as the temperature. Ie if the logged temperature is, for example, 25.87*C the capacitance is 25 etc.

Reverting to version 1.3.1 of the seesaw library the capacitance is within the range expected, ie with the sensor in the air it is greater than 300.

The sensor is connected as per https://learn.adafruit.com/adafruit-stemma-soil-sensor-i2c-capacitive-moisture-sensor/arduino-test

**Comment by ladyada** [comment]
what board are you using to read the sensor? we cannot reproduce this issue :/

**Comment by juliant99** [comment]
I'm using the Arduino Uno - R3 .

**Comment by ladyada** [comment]
ok try 1.4.1 please!

**Comment by juliant99** [comment]
Yep, works now - many thanks
