### ISSUE TITLE
Example for using multiple seesaw ATtiny817 BoBs?

### ISSUE THREAD

**Issue by stevempotter** [adafruit/Adafruit_Seesaw#70]
I am using a lot of GPIOs and have now exceeded the number available on one SEESAW ATtiny817 board. I would like to chain two with the I2C connectors. Does each board need to have its own I2C address? I can't find any Examples (Arduino) that show how to set this up and how to specify which board I am reading or writing to. Does each board have to have its own interrupt line to signal GPIO transitions or are they ganged? Can you bulk-poll both boards with one command? 

Can you please point me to that information or some sample code? Ideally, it should be in the board's documentation, but I could not find it, nor in the Seesaw Examples.

**Comment by caternuson** [comment]
> Does each board need to have its own I2C address?

Yes. Use the address pins to set unique addresses for each:
https://learn.adafruit.com/adafruit-attiny817-seesaw/pinouts#seesaw-i2c-address-pins-3104183-8
and then pass in the non-default addresses when calling begin:
https://adafruit.github.io/Adafruit_Seesaw/html/class_adafruit__seesaw.html#a89d53d9ef5afd6cef0449962de34d90a

> Does each board have to have its own interrupt line to signal GPIO transitions or are they ganged?

Yes
https://learn.adafruit.com/adafruit-attiny817-seesaw/pinouts#seesaw-interrupt-pins-3104178-7

> Can you bulk-poll both boards with one command?

No. Each would be a separate I2C device that you would communicate with separately.
