### ISSUE TITLE
ATtiny817 Arduino Input Pullups

### ISSUE THREAD

**Issue by el-samiyel** [adafruit/Adafruit_Seesaw#79]
- Arduino board:  **Arduino zero**

- Arduino IDE version (found in Arduino -> About Arduino menu):  2.0

INPUT_PULLUP doesn't seem to be implemented for the ATtiny817 on Arduino, but has been implemented on python.

https://learn.adafruit.com/adafruit-attiny817-seesaw/digital-input

Is there an update coming?

Cheers

**Comment by ladyada** [comment]
hiya, not sure what you mean, we have INPUT_PULLUP in the library - is there an example that you have written that does not work as expected?

**Comment by caternuson** [comment]
Closing due to lack of response. Can reopen if example sketch provided.
