### ISSUE TITLE
examples/miniTFTWing/basic LEFT / RIGHT triangles swapped

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Seesaw#8]
Triangles drawn to display for LEFT / RIGHT joystick seem to be swapped in examples/miniTFTWing/basic/basic.ino.

**Comment by ladyada** [comment]
hold on lemme write a guide for this and fix/test everything

**Comment by ladyada** [comment]
i removed, fixed and put in the other library. see:
https://learn.adafruit.com/adafruit-mini-tft-featherwing
thx!

**Comment by caternuson** [comment]
Cool. Thanks. Closing PR #9 without merging.
