### ISSUE TITLE
Allow Alternative Wires for miniTFTWing

### ISSUE THREAD

**Issue by shen-tian** [adafruit/Adafruit_Seesaw#80]
RP2040 feathers seem to use Wire1 for the standard I2C pins, so we need to be able to specify `Wire1`

Required to fix adafruit/Adafruit-ST7735-Library#185

**Comment by ladyada** [comment]
please try 
https://github.com/adafruit/Adafruit_Seesaw/pull/85

**Comment by caternuson** [comment]
Closing due to lack of response. Should be fixed by #85.
